backend:
  name: git-gateway
  repo: dillonbrowne/brax
  logo: 'https://d33wubrfki0l68.cloudfront.net/339af5c254abadb1f774a4f4a6b8ac1cfe1b9bb9/b517e/img/dillon-browne-dark.png'

media_folder: src/images
public_folder: images

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/data/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
